### ISSUE TITLE
Admin Panel Picture

### ISSUE THREAD

**Issue by AmmarOnah** [ahmedshamsddin/internship-application#1]
So it's only bars above each other, each bar contains user name with 2 button besides it one for acception & the other for rejection. should I worry about the usernames bars (use special thing for them) or I can write them in anyway (lets say using h3 header) and the backend will figure it out ?

**Comment by ahmedshamsddin** [comment]
Yes you can create it as table too (use <table> tag), The names will be unique for each one and they should be links (<a> tags). In the backend we will configure the links for each name

**Comment by AmmarOnah** [comment]
alright thanks
